/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrialRouteImport } from './routes/_authenticated/trial'
import { Route as AuthenticatedMobileRouteImport } from './routes/_authenticated/mobile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVisitIdRouteImport } from './routes/_authenticated/visit.$id'
import { Route as AuthenticatedConversationIdRouteImport } from './routes/_authenticated/conversation.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrialRoute = AuthenticatedTrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMobileRoute = AuthenticatedMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitIdRoute = AuthenticatedVisitIdRouteImport.update({
  id: '/visit/$id',
  path: '/visit/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversationIdRoute =
  AuthenticatedConversationIdRouteImport.update({
    id: '/conversation/$id',
    path: '/conversation/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mobile': typeof AuthenticatedMobileRoute
  '/trial': typeof AuthenticatedTrialRoute
  '/conversation/$id': typeof AuthenticatedConversationIdRoute
  '/visit/$id': typeof AuthenticatedVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mobile': typeof AuthenticatedMobileRoute
  '/trial': typeof AuthenticatedTrialRoute
  '/conversation/$id': typeof AuthenticatedConversationIdRoute
  '/visit/$id': typeof AuthenticatedVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mobile': typeof AuthenticatedMobileRoute
  '/_authenticated/trial': typeof AuthenticatedTrialRoute
  '/_authenticated/conversation/$id': typeof AuthenticatedConversationIdRoute
  '/_authenticated/visit/$id': typeof AuthenticatedVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/login'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/mobile'
    | '/trial'
    | '/conversation/$id'
    | '/visit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/login'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/mobile'
    | '/trial'
    | '/conversation/$id'
    | '/visit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/how-it-works'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/mobile'
    | '/_authenticated/trial'
    | '/_authenticated/conversation/$id'
    | '/_authenticated/visit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trial': {
      id: '/_authenticated/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof AuthenticatedTrialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mobile': {
      id: '/_authenticated/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof AuthenticatedMobileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visit/$id': {
      id: '/_authenticated/visit/$id'
      path: '/visit/$id'
      fullPath: '/visit/$id'
      preLoaderRoute: typeof AuthenticatedVisitIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversation/$id': {
      id: '/_authenticated/conversation/$id'
      path: '/conversation/$id'
      fullPath: '/conversation/$id'
      preLoaderRoute: typeof AuthenticatedConversationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMobileRoute: typeof AuthenticatedMobileRoute
  AuthenticatedTrialRoute: typeof AuthenticatedTrialRoute
  AuthenticatedConversationIdRoute: typeof AuthenticatedConversationIdRoute
  AuthenticatedVisitIdRoute: typeof AuthenticatedVisitIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMobileRoute: AuthenticatedMobileRoute,
  AuthenticatedTrialRoute: AuthenticatedTrialRoute,
  AuthenticatedConversationIdRoute: AuthenticatedConversationIdRoute,
  AuthenticatedVisitIdRoute: AuthenticatedVisitIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
